# Generated by Django 4.2.1 on 2024-07-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['-time_create'], name='person_pers_time_cr_3fd1cb_idx'),
        ),
    ]
