# Generated by Django 4.2.1 on 2024-07-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_category_person_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.category'),
        ),
    ]
